version: "2"

run:
  timeout: 5m
  tests: false

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - gocyclo
    - goconst
    - unparam
    - prealloc
    - revive
    - misspell
    - unconvert
    - nakedret
    - dogsled
    - copyloopvar
  settings:
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 3
      min-occurrences: 3
    misspell:
      locale: US
      ignore-rules:
        - cancelled
    revive:
      rules:
        - name: exported
          disabled: false
        - name: package-comments
          disabled: false
